# Generated by Django 3.2.6 on 2021-08-08 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('brand_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10)),
                ('seq_num', models.SmallIntegerField(default=1)),
                ('customer_po', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.CharField(max_length=30)),
                ('order_type', models.CharField(max_length=2)),
                ('order_date', models.DateField()),
                ('rtd', models.DateField(blank=True, null=True)),
                ('etd', models.DateField(blank=True, null=True)),
                ('brand', models.CharField(max_length=30)),
                ('item', models.CharField(max_length=50)),
                ('color_code', models.CharField(max_length=30)),
                ('pattern', models.CharField(max_length=30)),
                ('spec', models.CharField(max_length=30)),
                ('order_qty', models.SmallIntegerField(default=0)),
                ('unit', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_step', models.CharField(blank=True, max_length=100, null=True)),
                ('material_type', models.CharField(blank=True, max_length=10, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('modify_log', models.TextField(blank=True, null=True)),
                ('state', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WatchlistInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opman.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_qty', models.IntegerField(default=0)),
                ('procedure', models.CharField(blank=True, max_length=10, null=True)),
                ('first_update', models.DateField(blank=True, null=True)),
                ('last_state', models.CharField(blank=True, max_length=30, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('plan_state', models.CharField(blank=True, max_length=30, null=True)),
                ('plan_date', models.DateField(blank=True, null=True)),
                ('state_last', models.CharField(blank=True, max_length=30, null=True)),
                ('date_last', models.DateField(blank=True, null=True)),
                ('plan_qty', models.SmallIntegerField(blank=True, null=True)),
                ('pd_state', models.CharField(blank=True, max_length=30, null=True)),
                ('pd_date', models.DateField(blank=True, null=True)),
                ('pd_qty', models.SmallIntegerField(blank=True, null=True)),
                ('bf_state', models.CharField(blank=True, max_length=30, null=True)),
                ('bf_date', models.DateField(blank=True, null=True)),
                ('bf_qty', models.SmallIntegerField(blank=True, null=True)),
                ('eb_state', models.CharField(blank=True, max_length=30, null=True)),
                ('eb_date', models.DateField(blank=True, null=True)),
                ('eb_qty', models.SmallIntegerField(blank=True, null=True)),
                ('pt_state', models.CharField(blank=True, max_length=30, null=True)),
                ('pt_date', models.DateField(blank=True, null=True)),
                ('pt_qty', models.SmallIntegerField(blank=True, null=True)),
                ('ins_state', models.CharField(blank=True, max_length=30, null=True)),
                ('ins_date', models.DateField(blank=True, null=True)),
                ('ins_qty', models.SmallIntegerField(blank=True, null=True)),
                ('shp_date', models.DateField(blank=True, null=True)),
                ('shp_qty', models.SmallIntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opman.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='watch_users',
            field=models.ManyToManyField(related_name='watchlist', through='opman.WatchlistInfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opman.order')),
            ],
        ),
    ]
